### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by betatim** [binder-examples/requirements#1]
(this applies to all examples)

We should add a license to all our example repositories.

My suggestion would be https://opensource.org/licenses/BSD-3-Clause

@yuvipanda @choldgraf you are the only two contributors to this repository, can you indicate in this thread if you agree to licensing this as BSD3? Or make a suggestion which license you prefer.

**Comment by choldgraf** [comment]
I'm happy with whatever license y'all are happy with!

**Comment by yuvipanda** [comment]
WFM! I generally prefer CC0 for examples that we intend for people to copy, but 3BSD is good too!
