### ISSUE TITLE
tsplot removed from seaborn

### ISSUE THREAD

**Issue by TyBalduf** [binder-examples/requirements#13]
Not a crucial issue, but the `tsplot` function was removed from seaborn earlier this year in v0.10.0. The corresponding plot still appears when the example binder is opened, but trying to rerun the cell leads to an error. The [Seaborn site](https://seaborn.pydata.org/whatsnew.html) says that `tsplot` can be replaced with `lineplot`.

**Comment by choldgraf** [comment]
ah good catch - wanna make a PR updating the code? I'd be happy to review

**Comment by minrk** [comment]
Thanks for the PR! Closed by #14
