### ISSUE TITLE
requirements.txt incomplete?

### ISSUE THREAD

**Issue by schluenz** [binder-examples/requirements#4]
at least in some environments (anaconda python3.6) pip won't install seaborn-0.8.1 dependencies scipy, pandas. Changing seaborn==0.9.* or adding scipy,pandas to requirements.txt would fix.

**Comment by choldgraf** [comment]
do you know if this will break with the current build of this repository? it is mostly meant as an example, so it's OK if it doesn't work on all environments / version of python / etc

**Comment by schluenz** [comment]
as the notes say "be as explicit as possible" I thought adding scipy, pandas would make sense.
I'm using the binder-examples to test a slurm_spawner-based kind-of-binder. very convenient. just the "import seaborn" fails due to missing scipy. no idea why my plain jupyterhub environment fails to pull the implicit seaborn dependencies. but you are right: it works fine in most environments, so please just disregard my "intrusion"

**Comment by choldgraf** [comment]
no intrusion at all! I just wanted to clarify how general the problem was, we appreciate you reaching out and bringing up the issue!
