### ISSUE TITLE
Consider making repo a GitHub template repository

### ISSUE THREAD

**Issue by matthewfeickert** [binder-examples/requirements#7]
As GitHub now allows for repos to be [template repositories](https://help.github.com/en/articles/creating-a-template-repository) that allow repos to be used as base seeds for others. It could be useful if this repo could be turned into one.

That being said, I'm not sure if that defeats the purpose if part of the idea of the repo is "hey, here's a really small example of how to do this, now having seen this please go take this information and make your own".

Example of a GitHub template repo: https://github.com/matthewfeickert/talk-template

**Comment by choldgraf** [comment]
Hmmm - what does being a "template repository" mean? Is it different from "importing" a repository into a user's account?

I could see the value in making the binder-examples repos template repositories, though not sure what are the implications...

**Comment by matthewfeickert** [comment]
> Is it different from "importing" a repository into a user's account?

Hm, sorry I don't think I quite know what you mean by "Importing".

I think perhaps it is easier to show what a template repo does. My [talk-template repo](https://github.com/matthewfeickert/talk-template) is a GitHub template repo

![talk-template](https://user-images.githubusercontent.com/5142394/65168405-0f232380-da0a-11e9-80c5-4bedd042f18d.png)

and so it has the "Use this template" button on it, that if clicked will allow you to create a new repo that isn't a fork, but essentially clones the template and then squashes the history into a single init commit.

![template_made](https://user-images.githubusercontent.com/5142394/65168508-4d204780-da0a-11e9-8843-c9e5ee3faf43.png)

An example of a repo that was generated from this template is [this repo for a recent talk](https://github.com/matthewfeickert/talk-IRIS-HEP-Institute-Retreat-2019).

This might not have been helpful (sorry!) but if I can give a better example please let me know.


> I could see the value in making the binder-examples repos template repositories, though not sure what are the implications...

I think it would just make it easier for people to have a decoupled repo  of an example where they can play around and do whatever they want that isn't a fork (if they just want a sandbox and aren't going to probably ever contribute back).

**Comment by choldgraf** [comment]
Thanks for the explanation! For reference, I was talking about [the github importer function](https://help.github.com/en/articles/importing-a-repository-with-github-importer) which seems similar.

The way you describe it seems good to me. Is it just a matter of going into each repo and switching on the feature that makes the "use this template" button show up?

**Comment by matthewfeickert** [comment]
> For reference, I was talking about [the github importer function](https://help.github.com/en/articles/importing-a-repository-with-github-importer) which seems similar.

Ah okay, thanks for showing me that. I've never used the importer before so perhaps it is similar.

> The way you describe it seems good to me. Is it just a matter of going into each repo and switching on the feature that makes the "use this template" button show up?

Yup! It is just a single toggle button click (**Template repository**) on the first page of the repo's Settings.

![template_option](https://user-images.githubusercontent.com/5142394/65464654-f65aa980-de1f-11e9-9993-c3d4c74d8423.png)

**Comment by choldgraf** [comment]
Nice - I just did this, so all the binder-examples repositories should now be one-click-copyable:-)
